#
# Providence
# Transforms
# DBT Staging Simplygo Source
#

version: 2

sources:
  - name: simplygo
    description: Public transport data scraped from SimplyGo on AWS S3 data lake.
    schema: lake
    tables:
      - name: source_simplygo
        description: Public transport trips data scraped from SimplyGo.
        columns:
          - name: scraped_on
            description: Timestamp when the data was scraped in Asia/Singapore timezone.
          - name: cards
            description: Bank cards registered on SimplyGo.
          - name: trips_from
            description: Date of the start of the time period on Trips were scraped.
          - name: trips_to
            description: Date of the end of the time period on Trips were scraped.
          - name: trips
            description: Public transport trips scraped from SimplyGo for the specified time period.
        freshness:
          warn_after:
            count: 1
            period: day
          error_after:
            count: 2
            period: day
        loaded_at_field: "convert_timezone('SGT', 'UTC', cast(scraped_on as timestamp))"
