#
# Providence
# Transforms
# Staging Models Config
# DBT Staging YNAB Source
#

version: 2

sources:
  - name: ynab
    description: YNAB accounting software data export on AWS S3 data lake.
    schema: lake
    tables:
      - name: source_ynab
        description: YNAB accounting software data export.
        columns:
          - name: id
            description: YNAB assigned budget id.
          - name: name
            description: Name of the budget
          - name: accounts
            description: List of Budget accounts.
          - name: categories
            description: List of Budget categories.
          - name: category_groups
            description: List of Budget category groupings.
          - name: currency_format
            description: Budget currency format configuration.
          - name: date_format
            description: Budget date format configuration.
          - name: first_month
            description: The first year-month the budget accounted for.
          - name: last_modified_on
            description: Timestamp the was Budget last modified on.
          - name: last_month
            description: The last year-month the budget accounted for.
          - name: months
            description: List of Monthly Budget allocation data.
          - name: payee_locations
            description: List of Payee location coordinates
          - name: payees
            description: List of Payee information
          - name: scheduled_subtransactions
            description: List of scheduled transactions
          - name: scheduled_transactions
            description: List of scheduled subtransactions
          - name: subtransactions
            description: List of subtransactions
          - name: transactions
            description: List of transactions
          - name: _ynab_src_scraped_on
            description: Timestamp when the data was scraped in UTC timezone.
        freshness:
          warn_after:
            count: 1
            period: day
          error_after:
            count: 2
            period: day
        loaded_at_field: "cast(_ynab_src_scraped_on as timestamp)"
