#
# Providence
# Transforms
# DBT Staging UOB Source
#

version: 2

sources:
  - name: uob
    description: UOB Bank statement export stored on AWS S3 data lake.
    meta:
      external_location: read_parquet("s3://{{ env_var('PVD_LAKE_BUCKET', 'mrzzy-co-data-lake') }}/staging/by=uob/*.pq")
    tables:
      - name: uob
        description: UOB Bank statement export.
        columns:
          - name: transaction date
            description: Date the bank transaction was made.
          - name: transaction description
            description: Description of the bank transaction.
          - name: withdrawal
            description: How much was withdrawn from the bank account by the transaction.
          - name: deposit
            description: How much was deposited into from the bank account by the transaction.
          - name: available balance
            description: Balance of the bank account available for use.
          - name: account number
            description: Bank account no.
          - name: account type
            description: Bank account type.
          - name: statement period
            description: Date range in which the bank statement covers.
          - name: currency
            description: Bank account currency.
