#
# Providence
# Transforms
# DBT Staging Manual Mappings Sources
#

version: 2

sources:
  - name: mapping
    description: >-
      Manually crafted mappings ingested as AWS Redshift tables. Allows allows
      otherwise unrelated data from disparate sources to be joined via a manual mapping.
    schema: "{{ var('schema') }}"
    tables:
      - name: map_account
        description: Mapping of YNAB budget account IDs to vendor-specific account IDs
        columns:
          - name: budget_account_id
            description: YNAB Budget Account ID to associate with Vendor account.
          - name: vendor
            description: Vendor hosting the vendor account.
          - name: vendor_id
            description: Vendor assigned account ID to associate with the YNAB Budget account.
      - name: map_bank_card
        description: Mapping of to SimplyGo Bank Card IDs to vendor-specific account IDs
        columns:
          - name: budget_account_id
            description: SimplyGo assigned Bank Card ID to associate with Vendor account.
          - name: vendor
            description: Vendor hosting the Vendor account.
          - name: vendor_id
            description: Vendor assigned account ID to associate with the Bank Card.
