#
# Providence
# pre-commit
#

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.22.0
  hooks:
    - id: check-github-workflows
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.16.1
  hooks:
    - id: gitleaks
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
  hooks:
  - id: codespell
    args: ["-I", ".codespellignore"]
