#
# Providence
# Docker Compose
#

services:
  # Minio to emulate cloud object storage (ie. s3) for local development
  minio:
    image: minio/minio:RELEASE.2023-06-09T07-32-12Z
    environment:
      # root user
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      # storage volume where minio write its data
      MINIO_VOLUMES: "/mnt/data"
    command:
      [
        "minio",
        "server",
        "--address",
        "0.0.0.0:9000",
        "--console-address",
        "0.0.0.0:9090",
      ]
    volumes:
      - minio-data:/mnt/data
    # use host networking airflow so task containers running within the kind k8s
    # cluster can access minio via bridge network gateway ip
    network_mode: host
    ports:
      # s3 object storage api port
      - 9000:9000
      # web console port
      - 9090:9090

  # Standalone Airflow for Development
  airflow:
    build: pipelines
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__LOAD_DEFAULT_CONNECTIONS: "False"
      # point airflow at sqlite db persisted by data volume
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "sqlite:////data/airflow.db"
      # user env vars from .env automatically loaded by compose to define
      # Airflow connections expected by Airflow DAGs. NOTE: These Airflow
      # connections would not appear in the Airflow UI as they are not stored in the DB.
      AIRFLOW_CONN_PVD_SIMPLYGO_SRC: |
        {
            "conn_type": "generic",
            "login": "${SIMPLYGO_SRC_USERNAME}",
            "password": "${SIMPLYGO_SRC_PASSWORD}"
        }
      AIRFLOW_CONN_YNAB_API: |
        {
            "conn_type": "generic",
            "password": "${YNAB_ACCESS_TOKEN}"
        }
      # expects an accessible kubernetes cluster via passed $KUBECONFIG
      AIRFLOW_CONN_KUBERNETES_DEFAULT: |
        {
          "conn_type": "kubernetes",
          "extra": {
            "kube_config_path": "/kubeconfig.yaml",
            "namespace": "default"
          }
        }
      # uses kubernetes cluster at access $KUBE_API_SERVER_HOST:$KUBE_API_SERVER_PORT
      # as spark cluster manager
      AIRFLOW_CONN_SPARK_SQL_DEFAULT: |
        {
          "conn_type": "spark",
          "host": "${KUBE_API_SERVER_HOST}",
          "port": ${KUBE_API_SERVER_PORT},
          "extra": {
            "deploy-mode":  "cluster",
          },
        }
      AIRFLOW_CONN_RCLONE_DEFAULT: |
        {
          "conn_type": "rclone",
          "extra": {
            "type": "s3",
            "provider": "Minio",
            "access_key_id": "${MINIO_ROOT_USER}",
            "secret_access_key": "${MINIO_ROOT_PASSWORD}",
            "endpoint": "http://172.24.0.1:9000"
          }
        }
      KUBECONFIG: /kubeconfig.yaml
    volumes:
      - "${KUBECONFIG}:/kubeconfig.yaml"
      - ./pipelines:/opt/airflow/dags
      - airflow-data:/opt/airflow/data
    ports:
      - 8080:8080
    # host networking is needed for airflow to access k8s
    network_mode: host

  # Superset for BI Dashboards
  superset:
    build: infra/services/superset
    ports:
      - 8088:8088
    environment:
      ADMIN_PASSWORD: "${SUPERSET_ADMIN_PASSWORD}"
    volumes:
      - superset-data:/data
volumes:
  minio-data:
  superset-data:
  airflow-data:

networks:
  providence:
    ipam:
      config:
        # fix the bridge network to 172.24.0.* subnet to force the gateway ip to be 172.24.0.1
        - subnet: 172.24.0.0/24
