#
# Providence
# Transforms
# DBT Profile
#

providence:
  outputs:
    # development: in-memory transient duckdb
    dev: &duckdb
      type: duckdb
      extensions:
        - httpfs
        - parquet
        - icu
        - motherduck
      settings:
        s3_region: ""
        s3_endpoint: "s3.us-west-004.backblazeb2.com"
        s3_access_key_id: "{{ env_var('B2_ACCOUNT_ID') }}"
        s3_secret_access_key: "{{ env_var('B2_APP_KEY') }}"
    dev_persist:
      <<: *duckdb
      path: "dev.db"
    # production: Motherduck data warehouse
    prod:
      <<: *duckdb
      path: "md:pvd"
  target: "{{ env_var('DBT_TARGET', 'dev') }}"

config:
  send_anonymous_usage_stats: false
