#
# Providence
# Data Pipeline
# S3FS Sidecar Pod template
# Allows base container to write to s3 transparently.
#

apiVersion: v1
kind: Pod
metadata: {}
spec:
  containers:
  - name: base
  - name: s3fs
    image: efrecon/s3fs:1.79
    env:
      - name: AWS_S3_BUCKET
        value: "{{ params.s3_bucket }}"
      - name: AWS_S3_ACCESS_KEY_ID
        value: "{{ conn.aws_default.login }}"
      - name: AWS_S3_SECRET_ACCESS_KEY
        value: "{{ conn.aws_default.password }}"
    volumeMounts:
      - name: s3-bucket
        mountPath: /opt/s3fs/bucket
  volumes:
    - name: s3-bucket
      emptyDir: {}
