[package]
name = "simplygo_src"
version = "0.1.0"
edition = "2021"
  description  = "Providence SimplyGo Data Source"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.24", features = ["serde"] }
clap = { version = "4.1.8", features = ["derive"] }
reqwest = { version = "0.11.14", features = ["blocking", "multipart"] }
scraper = "0.15.0"
