#
# Providence
# CI Workflow
#

name: Providence CI
on: push
jobs:
  simplygo-src:
    name: "SimplyGo Source"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: |
          make lint-simplygo
      - name: Build
        run: |
          make build-simplygo
      - name: Test
        run: |
          make test-simplygo
