#
# Providence
# CI Workflow
#

name: Providence CI
on: push
env:
  CONTAINER_REGISTRY: ghcr.io
jobs:
  simplygo-src:
    name: "SimplyGo Source: Lint Build & Test"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: |
          make lint-simplygo
      - name: Build
        run: |
          make build-simplygo
      - name: Test
        env:
          SIMPLYGO_SRC_USERNAME: "${{ secrets.SIMPLYGO_SRC_USERNAME }}"
          SIMPLYGO_SRC_PASSWORD: "${{ secrets.SIMPLYGO_SRC_PASSWORD }}"
          AWS_DEFAULT_REGION: "ap-southeast-1"
          AWS_S3_TEST_BUCKET: "mrzzy-co-dev"
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        run: |
          make test-simplygo

  pipelines:
    name: "Airflow Pipelines: Lint Build & Test"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.6"
      - name: Setup dependencies
        run: make deps-pipelines
      - name: Lint
        run: make lint-pipelines
      - name: Test
        run:
          make test-pipelines

  src-container:
    strategy:
      fail-fast: false
      matrix:
        source:
          - simplygo
    name: "${{ matrix.source }} Source: Publish Container image"
    runs-on: ubuntu-22.04
    # add permissions needed to push containers to GHCR with GITHUB_TOKEN
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: docker-metadata
        name: "Gather metadata for tagging / labeling ${{ matrix.source }} Container"
        uses: docker/metadata-action@v4.3.0
        with:
          images: "${{ env.CONTAINER_REGISTRY }}/${{ github.repository_owner }}/\
                   providence-${{ matrix.source }}-src"
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            # set latest tag for default branch (main)
            type=raw,value=latest,enable={{is_default_branch}}
      - name: "Build and Push ${{ matrix.source }} Container to GitHub Container Registry"
        uses: docker/build-push-action@v4.0.0
        with:
          context: "sources/${{ matrix.source }}"
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          push: true

  e2e-test:
    name: "End to End Test"
    runs-on: ubuntu-22.04
    env:
      KUBECONFIG: /tmp/kubeconfig.yaml
    steps:
    - uses: actions/checkout@v3
    - uses: engineerd/setup-kind@v0.5.0
      with:
        version: v0.11.1
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10.6"
    - name: Setup dependencies
      run: pip install -r tests/requirements.txt
    - name: Test
      working-directory: tests
      env:
        SIMPLYGO_SRC_USERNAME: "${{ secrets.SIMPLYGO_SRC_USERNAME }}"
        SIMPLYGO_SRC_PASSWORD: "${{ secrets.SIMPLYGO_SRC_PASSWORD }}"
        AWS_DEFAULT_REGION: "ap-southeast-1"
        AWS_S3_TEST_BUCKET: "mrzzy-co-dev"
        AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      run: pytest
