#
# Providence
# DBT CI Workflow
#

name: Providence DBT CI
env:
  PYTHON_VERSION: 3.10.6
on:
  push:
    paths:
      - ".github/workflows/dbt.yaml"
      - "transforms/dbt/**"
jobs:
  dbt-transform:
    name: "DBT Transform: Lint, Build & Test"
    runs-on: ubuntu-22.04
    env:
      AWS_REDSHIFT_USER: "${{ secrets.AWS_REDSHIFT_USER }}"
      AWS_REDSHIFT_PASSWORD: "${{ secrets.AWS_REDSHIFT_PASSWORD }}"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
      - name: Setup dependencies
        run: make deps-dbt
      - name: Lint
        run: make lint-dbt
      # Deploy DBT model to development env
      - name: Build development
        run: make build-dbt DBT_TARGET=dev
      - name: Test development
        run: make test-dbt DBT_TARGET=dev
      # Deploy DBT model to production env
      - name: Build production
        if: ${{ github.ref == 'refs/heads/main' }}
        run: make build-dbt DBT_TARGET=prod
      - name: Test production
        if: ${{ github.ref == 'refs/heads/main' }}
        run: make test-dbt DBT_TARGET=prod

  dbt-docs:
    name: "DBT Docs"
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
      - name: Setup dependencies
        run: make deps-dbt
      - name: Generate docs
        env:
          AWS_REDSHIFT_USER: "${{ secrets.AWS_REDSHIFT_USER }}"
          AWS_REDSHIFT_PASSWORD: "${{ secrets.AWS_REDSHIFT_PASSWORD }}"
        working-directory: transforms/dbt
        run: |
          set -ex -o pipefail
          # generate docs into 'target' dir
          dbt docs generate
          # create 'docs' dir containing only the files needed for dbt docs
          mkdir docs
          cp target/{index.html,manifest.json,catalog.json} -t docs
      - name: Publish docs
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: transforms/dbt/docs
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          full_commit_message: "doc(transform): update dbt docs for ${{ github.sha }}"
