#
# Providence
# Simplygo Workflow
# SimplyGO Source Task
#

on:
  workflow_dispatch:
    inputs:
      trips_on:
        description: Date from which trips are scraped from SimplyGo in format YYYY-MM-DD.
        required: true
        type: string
      image:
        description: Fully qualified simplygo-src container image to use to scrape.
        default: ghcr.io/mrzzy/pvd-simplygo-tfm:latest
        type: string
jobs:
  scrape-simplygo:
    runs-on: ubuntu-latest
    container:
      image: "${{ inputs.image }}"
      env:
        SIMPLYGO_SRC_USERNAME: "${{ secrets.SIMPLYGO_SRC_USERNAME }}"
        SIMPLYGO_SRC_PASSWORD: "${{ secrets.SIMPLYGO_SRC_PASSWORD }}"
        RCLONE_B2_ACCOUNT: "${{ secrets.RCLONE_B2_ACCOUNT }}"
        RCLONE_B2_KEY: "${{ secrets.RCLONE_B2_KEY }}"
        RCLONE_B2_HARD_DELETE: true
    steps:
      - name: Scrape SimplyGo with SimplyGo source
        run: "simplygo_src --trips-from ${{ inputs.trips_on }} --trips-to ${{ inputs.trips_on }} --output out"
      - name: Copy scraped data to B2
        run: "rclone copy --size-only --fast-list out b2:mrzzy-co-data-lake/raw/date=${{ inputs.trips_on }}"
