#
# Providence
# Simplygo Workflow
# SimplyGO Transform Task
#

name: "SimplyGo: Transform Task"
on:
  workflow_dispatch:
    inputs:
      trips_on:
        description: Date from which trips are scraped from SimplyGo in format YYYY-MM-DD.
        required: true
        type: string
      image:
        description: Fully qualified simplygo-tfm image tag to use to scrape.
        default: ghcr.io/mrzzy/pvd-simplygo-tfm:latest
        type: string
jobs:
  scrape-simplygo:
    runs-on: ubuntu-latest
    container:
      image: "${{ inputs.image }}"
      env:
        SIMPLYGO_SRC_USERNAME: "${{ secrets.SIMPLYGO_SRC_USERNAME }}"
        SIMPLYGO_SRC_PASSWORD: "${{ secrets.SIMPLYGO_SRC_PASSWORD }}"
        RCLONE_B2_ACCOUNT: "${{ secrets.RCLONE_B2_ACCOUNT }}"
        RCLONE_B2_KEY: "${{ secrets.RCLONE_B2_KEY }}"
        RCLONE_B2_HARD_DELETE: true
    steps:
      - name: Copy scraped data to B2
        run: "rclone copy --size-only --fast-list :b2:mrzzy-co-data-lake/staging/by=simplygo_src/date=${{ inputs.trips_on }} /tmp/raw"
      - name: Transform SimplyGo Raw Data to CSV
        run: "simplygo_tfm --input-dir /tmp/raw --output /tmp/out.csv"
      - name: Copy scraped data to B2
        run: "rclone copy --size-only --fast-list /tmp/out.csv :b2:mrzzy-co-data-lake/staging/by=simplygo-tfm/date=${{ inputs.trips_on }}/out.csv"
